name: Java CI

on: [push, pull_request]

jobs:
  build-macos-arm:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get dependent binaries from cache
      uses: actions/cache@v4
      with:
        path: ./dependencies
        key: swt-jface-lwjgl3zip-tools-macos-arm-v5
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 21
    - name: Build with Ant
      run: ant -noinput -buildfile build-macos-arm.xml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      with:
        check_name: junit-macos-arm
        report_paths: '**/report/TEST-*.xml'
        fail_on_failure: true
        require_passed_tests: true
